server:
  port: 9003

spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
  rabbitmq:
    host: ${RABBIT_HOST:127.0.0.1} #rabbitmq地址
    port: 5672 #端口号
    virtual-host: / #主机
    username: ${RABBIT_USER:admin}
    password: ${RABBIT_PASSWORD:admin}
    #开启手动确认
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: 6379
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/shop_order_1024?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USER:root}
    password: ${DB_PWD:1234}



#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO
QNY: ${QINIU_DOMAIN:}
AK: ${QINIU_ACCESS_KEY:}
SK: ${QINIU_SECRET_KEY:}
Bucket: ${QINIU_BUCKET:}

#自定义消息队列配置，发送锁定库存消息-》延迟exchange-》lock.queue-》死信exchange-》release.queue
mqconfig:
  #延迟队列，不能被监听消费
  order_close_delay_queue: order.close.delay.queue.v3

  #延迟队列的消息过期后转发的队列
  order_close_queue: order.close.queue.v3

  #交换机
  order_event_exchange: order.event.exchange.v3

  #进入延迟队列的路由key
  order_close_delay_routing_key: order.close.delay.routing.key.v3

  #消息过期，进入释放队列的key,进入死信队列的key
  order_close_routing_key: order.close.routing.key.v3

  #消息过期时间,毫秒,测试改为15秒
  ttl: 1800000



alibabaPay:
  alipayPublicKey: ${ALIPAY_PUBLIC_KEY:}
  privateKey: ${ALIPAY_PRIVATE_KEY:}
  setServerUrl: ${ALIPAY_SERVER_URL:https://openapi-sandbox.dl.alipaydev.com/gateway.do}
  setAppId: ${ALIPAY_APP_ID:}
  NotifyUrl: ${ALIPAY_NOTIFY_URL:http://localhost:9003/api/callback/v1/alipay}
  returnUrl: ${ALIPAY_RETURN_URL:http://localhost:5173/user/orders}
