server:
  port: 9004
spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  application:
    name: coupon-service
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: 6379
  cloud:
     nacos:
       discovery:
         server-addr: ${NACOS_ADDR:127.0.0.1:8848}
  rabbitmq:
    host: ${RABBIT_HOST:127.0.0.1} #rabbitmq地址
    port: 5672 #端口号
    virtual-host: / #主机
    username: ${RABBIT_USER:admin}
    password: ${RABBIT_PASSWORD:admin}
    #开启手动确认
    listener:
      simple:
        acknowledge-mode: manual

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/shop_coupon_1024?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USER:root}
    password: ${DB_PWD:1234}



#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO
QNY: ${QINIU_DOMAIN:}
AK: ${QINIU_ACCESS_KEY:}
SK: ${QINIU_SECRET_KEY:}
Bucket: ${QINIU_BUCKET:}
##seata配置
#seata:
#  tx-service-group: ${spring.application.name}-group
#  service:
#    grouplist:
#      buka: 127.0.0.1:8091
#    vgroup-mapping:
#      coupon-service-group: buka
#自定义消息队列配置，发送锁定库存消息-》延迟exchange-》lock.queue-》死信exchange-release.queue
mqconfig:
  #延迟队列，不能被监听消费
  coupon_release_delay_queue: coupon.release.delay.queue

  #延迟队列的消息过期后转发的队列
  coupon_release_queue: coupon.release.queue

  #交换机
  coupon_event_exchange: coupon.event.exchange

  #进入延迟队列的路由key
  coupon_release_delay_routing_key: coupon.release.delay.routing.key

  #消息过期，进入释放死信队列的key
  coupon_release_routing_key: coupon.release.routing.key

  #消息过期时间,毫秒,测试改为15秒
  ttl: 1800000

